use crate::provider::{ProviderError, ProviderId};

#[derive(Debug)]
pub enum RuntimeError {
    ProviderNotFound(Option<ProviderId>),
    FailedToSendRequest(ProviderError),
    FailedToListModels(ProviderError),
    FailedToStreamResponse(ProviderError),
    FailedToCompactHistory(ProviderError),
    FailedToPersistTranscript(std::io::Error),
    FailedToSerializeTranscript(serde_json::Error),
    FailedToLoadTasks(std::io::Error),
    FailedToWriteTasks(std::io::Error),
    FailedToSerializeTasks(serde_json::Error),
    FailedToRestoreTasks(std::io::Error),
    FailedToLoadTeam(std::io::Error),
    FailedToWriteTeam(std::io::Error),
    FailedToSerializeTeam(serde_json::Error),
    FailedToDeserializeTeam(serde_json::Error),
    InvalidTask(String),
    InvalidTeam(String),
    OperationDenied(String),
    Store(String),
    LeaseUnavailable(String),
    Cancelled,
    DeadlineExceeded,
    ToolBudgetExceeded(usize),
    ModelBudgetExceeded(usize),
    MaxRoundsExceeded(usize),
    InvalidToolUseInput {
        id: String,
        name: String,
        source: serde_json::Error,
    },
    MalformedProviderEvent(String),
}
